BrowserPreferencesPage.java: override isValidFragment method
since following crash was reported when run monkey test:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.browser/com.android.browser.BrowserPreferencesPage}:
java.lang.RuntimeException: Subclasses of PreferenceActivity must override isValidFragment(String) to verify that the Fragment class is valid!
com.android.browser.BrowserPreferencesPage has not checked if fragment com.android.browser.preferences.GeneralPreferencesFragment is valid.

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>